### ISSUE TITLE
Estructura principal de la aplicación

### ISSUE THREAD

**Issue by josem-perram** [iesalonsodemadrigal/android-avila-diary#1]
## Descripción
Se desea desarrollar la estructura principal de la aplicación. La aplicación tendrá un MainActivity y las secciones principales: Agenda, RSS, Información, Eventos y Perfil.

Vamos a distinguir entre eventos y agenda. Agenda lo vamos a relacionar con aquellos eventos organizados por el ayuntamiento como puede ser la semana santa, circo del sol, ávila en tapas, etc. Eventos lo vamos a relaciones con empresas privadas: quedada para jugar a juegos de mesa, concierto en un bar, etc.

### Definición de hecho
- [ ] Creación de un menú navigation con los fragmentos: diary, rss, information, events, profile.
- [ ] Navegación segura entre los cinco fragmentos.
- [ ] Hilt: Application y MainActivity

**Comment by DavidCaidas** [comment]
issue finalizado
