### ISSUE TITLE
Profile: Listado de Desarrolladores

### ISSUE THREAD

**Issue by jmperezra** [iesalonsodemadrigal/android-avila-diary#14]
## Descripción

En el perfil del usuario, habrá una opción que va a mostrar el listado de desarrolladores de la app. 

De los desarrolladores se almacenará: nombre y apellidos, url de la imagen del desarrollador, profesión, enlace a su perfil (seguramente linkedin)

### Definición de hecho
- [ ] Caso de uso que recoja el listado de desarrolladores.
- [ ] Modelos, clases necesarias.
- [ ] Repositorio para la gestión de los desarrolladores.

**Comment by amrubio27** [comment]
Finalizado y listo
