### ISSUE TITLE
Events: Listado de eventos privados [Domain]

### ISSUE THREAD

**Issue by josem-perram** [iesalonsodemadrigal/android-avila-diary#5]
## Descripción

Se desea recuperar el listado de eventos privados. Los eventos tendrán la siguiente información: id, title, description, url_image, date_start, date_end, source.

### Definición de hecho
- [ ] Desarrollo del caso de uso necesario.
- [ ] Desarrollo de modelos.

**Comment by Pabloyquemas** [comment]
finalizado
